name: Deployment pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  URL: https://fullstackopen-part11-phonebook.onrender.com/

jobs:
  tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install backend dependencies
        run: npm i
      - name: Run eslint
        run: npm run lint
      - name: Install frontend dependencies
        run: cd frontend && npm i
      - name: Check lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      # - name: Install dependencies
      #   run: npm ci
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      # - name: Run Playwright tests
      #   run: npx playwright test
      # - uses: actions/upload-artifact@v4
      #   if: ${{ !cancelled() }}
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30

  deploy:
    needs: [tests]
    if: github.ref == 'refs/heads/main' && !contains(toJson(github.event.commits), '#skip')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
      - name: Deploy success
        uses: tsickert/discord-webhook@v6.0.0
        if: success()
        with:
          username: Mikko Kirkanen - GitHub
          avatar-url: https://cdn-icons-png.flaticon.com/64/6864/6864004.png
          content: ✅ Deployment Succeeded!
          embed-color: 65280
          embed-title: Information
          embed-description: |
            "**Repository:** [${{github.repository}}](${{github.event.repository.html_url}})"
            "**ULR:** [${{ env.URL }}](${{ env.URL }})"
          embed-footer-text: Deploy icons created by kerismaker - Flaticon
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}

  discord_build_failure:
    needs: [tests]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Build Failure
        uses: tsickert/discord-webhook@v6.0.0
        with:
          username: Mikko Kirkanen - GitHub
          avatar-url: https://cdn-icons-png.flaticon.com/64/6818/6818112.png
          content: ❌ Build Failed!
          embed-color: 16711680
          embed-title: Information
          embed-description: |
            "**Repository:** [${{github.repository}}](${{github.event.repository.html_url}})"
            "**ULR:** [${{ env.URL }}](${{ env.URL }})"
          embed-footer-text: Failed icons created by Prashanth Rapolu 15 - Flaticon
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
